# Docker compose file for testing. Use it with:
# docker-compose up --force-recreate
# This would pick up dgraph binary from $GOPATH.

version: "3.5"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  zero1:
    image: dgraph/dgraph:latest
    container_name: bank-dg0.1
    working_dir: /data/dg0.1
    ports:
      - 5080:5080
      - 6080:6080
    command: /gobin/dgraph zero --my=zero1:5080 --idx 1 --bindall --expose_trace --profile_mode block --block_rate 10 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      # - type: bind
      #   source: "${DATA}"
      #   target: /data

  # zero2:
  #   image: dgraph/dgraph:latest
  #   container_name: bank-dg0.2
  #   command: /gobin/dgraph zero -o 2 --my=zero2:5082 --peer=zero1:5080 --idx 2 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268
  #   depends_on:
  #     - zero1
  #   ports:
  #     - 5082:5082
  #     - 6082:6082
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true

  # zero3:
  #   image: dgraph/dgraph:latest
  #   container_name: bank-dg0.3
  #   command: /gobin/dgraph zero -o 3 --my=zero3:5083 --peer=zero1:5080 --idx 3 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268

  #   depends_on:
  #     - zero2
  #   ports:
  #     - 5083:5083
  #     - 6083:6083
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true

  # zero4:
  #   image: debian:latest
    # image: dgraph/dgraph:latest
  #   container_name: bank-dg0.4
  #   command: /gobin/dgraph zero --my=zero4:5080 --replicas 3 --peer=zero1:5080 --idx 4
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true

  # zero5:
  #   image: debian:latest
    # image: dgraph/dgraph:latest
  #   container_name: bank-dg0.5
  #   command: /gobin/dgraph zero --my=zero5:5080 --replicas 3 --peer=zero1:5080 --idx 5
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true

  dg1:
    image: dgraph/dgraph:latest
    container_name: bank-dg1
    working_dir: /data/dg1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      # - type: bind
      #   source: "${DATA}"
      #   target: /data
    ports:
      - 8180:8180
      - 9180:9180
    command: /gobin/dgraph alpha --my=dg1:7180 --lru_mb=1024 --zero=zero1:5080 -o 100 --expose_trace  --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268

  dg2:
    image: dgraph/dgraph:latest
    container_name: bank-dg2
    working_dir: /data/dg2
    depends_on:
      - dg1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      # - type: bind
      #   source: "${DATA}"
      #   target: /data
    ports:
      - 8182:8182
      - 9182:9182
    command: /gobin/dgraph alpha --my=dg2:7182 --lru_mb=1024 --zero=zero1:5080 -o 102 --expose_trace  --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268

  dg3:
    image: dgraph/dgraph:latest
    container_name: bank-dg3
    working_dir: /data/dg3
    depends_on:
      - dg2
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      # - type: bind
      #   source: "${DATA}"
      #   target: /data
    ports:
      - 8183:8183
      - 9183:9183
    command: /gobin/dgraph alpha --my=dg3:7183 --lru_mb=1024 --zero=zero1:5080 -o 103 --expose_trace   --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=3 --jaeger.collector=http://jaeger:14268

  # dg4:
  #   image: debian:latest
    # image: dgraph/dgraph:latest
  #   container_name: bank-dg4
  #   working_dir: /data/dg4
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true
  #     # - type: bind
  #     #   source: "${DATA}"
  #     #   target: /data
  #   ports:
  #     - 8184:8184
  #     - 9184:9184
  #   command: /gobin/dgraph alpha --my=dg4:7184 --lru_mb=1024 --zero=zero1:5080 -o 104 --expose_trace   --trace 1.0 --profile_mode block --block_rate 10

  # dg5:
  #   image: debian:latest
    # image: dgraph/dgraph:latest
  #   container_name: bank-dg5
  #   working_dir: /data/dg5
  #   volumes:
  #     - type: bind
  #       source: $GOPATH/bin
  #       target: /gobin
  #       read_only: true
  #     # - type: bind
  #     #   source: "${DATA}"
  #     #   target: /data
  #   ports:
  #     - 8185:8185
  #     - 9185:9185
  #   command: /gobin/dgraph alpha --my=dg5:7185 --lru_mb=1024 --zero=zero1:5080 -o 105 --expose_trace   --trace 1.0 --profile_mode block --block_rate 10

